# Generated by Django 3.2.6 on 2021-08-07 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210807_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='coordinator',
        ),
        migrations.RemoveField(
            model_name='account',
            name='student',
        ),
        migrations.RemoveField(
            model_name='account',
            name='teacher',
        ),
    ]
