# Generated by Django 3.2.6 on 2021-08-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210807_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='description',
            field=models.TextField(default='qew', verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
