# Generated by Django 3.2.6 on 2021-08-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210809_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='static/user', verbose_name='photo'),
        ),
    ]
