# Generated by Django 3.2.6 on 2021-08-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='title',
            field=models.CharField(default=' ', max_length=100, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
