# Generated by Django 3.2.6 on 2021-08-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_alter_course_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='color',
            field=models.CharField(choices=[('primary', 'Синий'), ('secondary', 'Фиолетовый'), ('success', 'Зеленый'), ('danger', 'Красный'), ('warning', 'Желтый'), ('info', 'Голубой'), ('light', 'Прозрачный'), ('dark', 'Черный')], default='primary', max_length=16, verbose_name='Цвет'),
        ),
    ]
