# Generated by Django 3.2.6 on 2021-08-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('education', '0006_group_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='photo',
            field=models.ImageField(default='', upload_to='static/education/course', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.AlterField(
            model_name='course',
            name='lessons',
            field=models.ManyToManyField(blank=True, to='education.Lesson', verbose_name='Уроки'),
        ),
    ]
