# Generated by Django 3.2.6 on 2021-08-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_auto_20210812_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='photo',
            field=models.ImageField(blank=True, upload_to='static/education/course', verbose_name='Фото'),
        ),
    ]
