# Generated by Django 3.2.6 on 2021-08-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_alter_course_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='color',
            field=models.CharField(choices=[('#ffaf00', 'Желтый'), ('#da2268', 'Розовый'), ('#bb02ff', 'Фиолетовый')], default='Желтый', max_length=7, verbose_name='Цвет'),
            preserve_default=False,
        ),
    ]
