# Generated by Django 3.2.6 on 2021-08-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_task_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(choices=[('#4169E1', 'Легкий уровень'), ('#ffaf00', 'Средний уровень'), ('#bb02ff', 'Сложный уровень')], max_length=7, verbose_name='Цвет'),
        ),
    ]
