# Generated by Django 3.2.6 on 2021-08-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_alter_task_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='price',
            field=models.FloatField(default=1000, verbose_name='Цена'),
        ),
    ]
