# Generated by Django 3.2.6 on 2021-08-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0013_auto_20210816_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Показать на странице'),
        ),
    ]
