# Generated by Django 3.2.6 on 2021-08-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0014_lesson_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Показать на странице'),
            preserve_default=False,
        ),
    ]
