# Generated by Django 3.2.6 on 2021-08-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0016_auto_20210817_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialblocks',
            name='color',
            field=models.CharField(choices=[('1', 'Голубой'), ('2', 'Розовый'), ('5', 'Фиолетовый'), ('4', 'Зеленый'), ('3', 'Розово-фиолетовый')], default='1', max_length=1),
            preserve_default=False,
        ),
    ]
