# Generated by Django 3.2.6 on 2021-08-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0017_materialblocks_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialblocks',
            name='color',
            field=models.CharField(choices=[('1', 'Голубой'), ('2', 'Розовый'), ('3', 'Фиолетовый'), ('4', 'Зеленый'), ('5', 'Розово-фиолетовый')], max_length=1),
        ),
    ]
