# Generated by Django 3.2.6 on 2021-08-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0018_alter_materialblocks_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialblocks',
            options={'verbose_name': 'Блок материала', 'verbose_name_plural': 'Блоки материала'},
        ),
        migrations.AlterField(
            model_name='materialblocks',
            name='block',
            field=models.FileField(upload_to='templates/education/material_sections', verbose_name='Информация блока'),
        ),
    ]
