# Generated by Django 3.2.6 on 2021-08-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0024_lesson_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(default='DC5XN38Hc2sehEePELEFzxQa4KuwPv2P', verbose_name='Код урока'),
        ),
    ]
