# Generated by Django 3.2.6 on 2021-08-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0025_alter_lesson_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(default='jFKUcdfCPnEZg6CgEv354UY9Jd5aqAXd', verbose_name='Код урока'),
        ),
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(choices=[('#95F49E', 'Легкий уровень'), ('#F9D648', 'Средний уровень'), ('#ac3d67', 'Сложный уровень')], max_length=7, verbose_name='Цвет'),
        ),
    ]
