# Generated by Django 3.2.6 on 2021-08-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0027_auto_20210826_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(default='bw7cz7AdUhEhrPnFSqDDxBBCrGhLyLrk', verbose_name='Код урока'),
        ),
    ]
