# Generated by Django 3.2.6 on 2021-08-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0028_alter_lesson_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(default='4F4EyqzWJY8BDegK73sLxYg2uANT5Tx3', verbose_name='Код урока'),
        ),
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(choices=[('#7BE29A', 'Легкий уровень'), ('#F9D648', 'Средний уровень'), ('#ac3d67', 'Сложный уровень')], max_length=7, verbose_name='Цвет'),
        ),
    ]
