# Generated by Django 3.2.6 on 2021-08-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0029_auto_20210826_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(default='DLVsturhhYC5VsS3sdWBWA2NMkZcLQuf', verbose_name='Код урока'),
        ),
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(choices=[('#57e283', 'Легкий уровень'), ('#F9D648', 'Средний уровень'), ('#ac3d67', 'Сложный уровень')], max_length=7, verbose_name='Цвет'),
        ),
    ]
