# Generated by Django 3.2.6 on 2021-08-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0030_auto_20210826_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(default='XfuMJs4dr9CuKFzWXsXMzvVzWLtNJcvd', verbose_name='Код урока'),
        ),
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(choices=[('#74EFA7', 'Легкий уровень'), ('#F9D648', 'Средний уровень'), ('#ac3d67', 'Сложный уровень')], max_length=7, verbose_name='Цвет'),
        ),
    ]
