# Generated by Django 3.2.6 on 2021-08-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0031_auto_20210826_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField(verbose_name='Входные данные')),
                ('output', models.TextField(verbose_name='Выходные данные')),
            ],
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(default='SJfdmqxTSFUkXP8Fedc7EwzTL2HDQXQp', verbose_name='Код урока'),
        ),
        migrations.AddField(
            model_name='task',
            name='examples',
            field=models.ManyToManyField(to='education.Examples', verbose_name='Примеры'),
        ),
    ]
