# Generated by Django 3.2.6 on 2021-08-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0032_auto_20210828_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='direction',
            field=models.CharField(choices=[('web', 'Web'), ('fb', 'Для начинающих'), ('bot', 'Боты'), ('back', 'Back'), ('front', 'Front'), ('ps', 'PhotoShop')], default='web', max_length=8, verbose_name=''),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('py', 'Python'), ('java', 'Java'), ('kotlin', 'Kotlin'), ('js', 'Java Script'), ('c++', 'c++'), ('c#', 'c#'), ('c', 'c'), ('np', 'Не программирование')], default='py', max_length=8, verbose_name=''),
        ),
        migrations.AddField(
            model_name='task',
            name='code',
            field=models.BooleanField(default=True, verbose_name='Код(да)/Ссылка(нет)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(default='4bhPMqyrzd3JUveVNpEbWhwHXb2dnQqF', verbose_name='Код урока'),
        ),
        migrations.AlterField(
            model_name='task',
            name='examples',
            field=models.ManyToManyField(blank=True, to='education.Examples', verbose_name='Примеры'),
        ),
    ]
