# Generated by Django 3.2.6 on 2021-08-30 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0036_auto_20210829_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(default='VUGUA6BF88p3HR5dqVDcujqM65h8CcFN', verbose_name='Код урока'),
        ),
        migrations.CreateModel(
            name='PaidLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.lesson', verbose_name='Урок')),
                ('solved_tasks', models.ManyToManyField(to='education.Task', verbose_name='Решенные задачи')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Человек')),
            ],
            options={
                'verbose_name': 'Оплаченный урок',
                'verbose_name_plural': 'Оплаченные уроки',
            },
        ),
    ]
