# Generated by Django 3.2.6 on 2021-08-30 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_account_photo'),
        ('education', '0037_auto_20210830_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(default='QjSpWsUzCvaYecRxMqu5kSwMFKYqZkVr', verbose_name='Код урока'),
        ),
        migrations.AlterField(
            model_name='paidlesson',
            name='solved_tasks',
            field=models.ManyToManyField(blank=True, to='education.Task', verbose_name='Решенные задачи'),
        ),
        migrations.AlterField(
            model_name='paidlesson',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student', verbose_name='Человек'),
        ),
    ]
