# Generated by Django 3.2.6 on 2021-08-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0038_auto_20210830_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(default='mWes4pFM5LjqX6872HZ7yvRttGNJz6Ek', unique=True, verbose_name='Код урока'),
        ),
    ]
