# Generated by Django 3.2.6 on 2021-08-31 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0040_auto_20210831_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(default='6QuRS7xCPDfrxqtw5K6VpMZFFhvdDPbm', unique=True, verbose_name='Код урока'),
        ),
    ]
