# Generated by Django 3.2.6 on 2021-09-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0041_alter_lesson_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delete',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(default='PnWpvFb6krJwNpr42hfwguFywANdQ5Pu', unique=True, verbose_name='Код урока'),
        ),
    ]
